stages:
  - stage: Dev
    displayName: Dev
    jobs:
      - job: DeployADF
        displayName: Deploy ADF
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '1.1.0'
          - task: TerraformTaskV1@0
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendServiceArm: 'your-arm-service-connection-NEW'
              backendAzureRmResourceGroupName: 'RS_Uma_Training01'
              backendAzureRmStorageAccountName: 'RS_Uma_Training01'
              backendAzureRmContainerName: 'test'
              backendAzureRmKey: '123567'
          - task: TerraformTaskV1@0
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceNameAzureRM: 'c614e646-d878-41af-8d21-74c639bf52b4'
              environmentServiceNameAzureRm: 'c614e646-d878-41af-8d21-74c639bf52b4'
